apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-attacher

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: external-attacher-runner
rules:
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshotclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshotcontents"]
    verbs: ["create", "get", "list", "watch", "update", "delete"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshotcontents/status"]
    verbs: ["update"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["list", "watch", "create", "update", "patch"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims/status"]
    verbs: ["patch"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshots"]
    verbs: ["get", "list"]  
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "create", "delete", "patch"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments"]
    verbs: ["get", "list", "watch", "patch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments/status"]
    verbs: ["patch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["csinodes"]
    verbs: ["get", "list", "watch", "update"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-attacher-role
subjects:
  - kind: ServiceAccount
    name: csi-attacher
    namespace: default
roleRef:
  kind: ClusterRole
  name: external-attacher-runner
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-nodeplugin
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-nodeplugin
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "watch", "create", "patch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-nodeplugin
subjects:
  - kind: ServiceAccount
    name: csi-nodeplugin
    namespace: default
roleRef:
  kind: ClusterRole
  name: csi-nodeplugin
  apiGroup: rbac.authorization.k8s.io  

---

kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: csi-attacher-sioplugin
spec:
  serviceName: "csi-attacher"
  replicas: 1
  selector:
    matchLabels:
      app: csi-attacher-sioplugin
  template:
    metadata:
      labels:
        app: csi-attacher-sioplugin
    spec:
      serviceAccount: csi-attacher
      hostNetwork: true
      containers:              
        - name: csi-provisioner
          image: k8s.gcr.io/sig-storage/csi-provisioner:v3.0.0
          args:
            - "--csi-address=\$(ADDRESS)" 
            - "--extra-create-metadata"   
            - "--feature-gates=Topology=true"            
          env:
            - name: ADDRESS
              value: /csi/csi.sock
          imagePullPolicy: "Always"
          volumeMounts:
            - name: socket-dir
              mountPath: /csi          

        - name: csi-attacher
          image: quay.io/k8scsi/csi-attacher:v3.1.0
          args:
            - "--v=5"
            - "--csi-address=\$(ADDRESS)"
          env:
            - name: ADDRESS
              value: /csi/csi.sock
          imagePullPolicy: "Always"
          volumeMounts:
            - name: socket-dir
              mountPath: /csi

        - name: vlz
          image:  public.ecr.aws/u0q8u2v6/volumez-csi:latest
          args :
            - "--nodeid=\$(NODE_ID)"
            - "--endpoint=\$(CSI_ENDPOINT)"
            - "--volumezendpoint=\$(VOLUMEZ_ENDPOINT)"
            - "--volumezEndpointBasePath=\$(VOLUMEZ_ENDPOINT_BASE_PATH)"
            - "--volumezauthtoken=\$(VOLUMEZ_AUTH_TOKEN)"            
            - "--run_connector=\$(RUN_CONNECTOR)"
            - "--connector_download_repository_base_url=\$(connector_download_repository_base_url)"
          env:
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: CSI_ENDPOINT
              value: unix://plugin/csi.sock
            - name: VOLUMEZ_ENDPOINT
              value: api.volumez.com
            - name: VOLUMEZ_ENDPOINT_BASE_PATH
              value:
            - name: VOLUMEZ_AUTH_TOKEN
              value: eyJjdHkiOiJKV1QiLCJlbmMiOiJBMjU2R0NNIiwiYWxnIjoiUlNBLU9BRVAifQ.DMI9SvdAD891pO18H_oWEahB8PKce4TREZHnV520IxL2Ub18DtspRBGMJ9Lu2Hfi1YFmKm0lmna_y8gMr_QQXrI5tK1OUr3Kwnfc1iXrGboNNo9FcdFgU2f3Pxt1o-sAykr6yiHYhBJ2lARwj1LHbNaZWXgW-8CkEwHGwz2S0NDmT1glemGCTEEQHhVRmwKlV9B4Go6BlH5qsPPSZXXfTCtLrykvlqgbi8OI-Nto6YJybcCHmbAaw7qYAekQgY53LgCOF_-Thflk_Cb5ToqeNIhis3SSJk9Cr6r2DLiaj-tHkwfz2mSFyupsQS2Vcl9x7aY5T3uxhKqdzjhctr-5CA.jvykCBRA7jRNCHey.VX8AJDQhp7xpEJ0ltuaOMRh0Y5c0yQ64I0Gc0L8xMY9AfXcDAnwc8sg1S5WMsnOMLDfZdaGLFIJ65x7E4RjxspyX4KNsWTTko8UFnTAqrkTnGOoobh2qKH3LnGzFTeZrjcFRr0HPG4P8eEwuag3rwcSNCkfLOl3PWxw912JrT9813bgrxdDcuBe2aWDJhdpBArfsM8xPQpUWs0d7hBDl2FuFSPUGq1h1Hk3oKrZoplE0SdvxG8UMcyWg7V0-0ZteJrrAuJt02GS0p960bYhBEMBoMy9ud7XOyXo3ns-GP1nF9vVASvX3Fukpm9NIVaZ1VYum8tUnvQ1QY8_jrjMwz_dY2ziKeljSKRULW_4jlSAOtETJX-CeB3KHJ5WtcBOgCorrhXFUa8sU6Uc4x7OR0b4s02BjIQzg-UYUQGbMy0iQKYOGzMoGwmsJlCwx-1iXZTrZRa5vADhPp_9L2M9yd3O1fL3cBAPdBAVbn9HnNIvcBhWidMjyzll_6Se5Kc_urAhGfR1-DDRnO_w6G2Qbwf5JXOTU2LnTov9vRYBbxuy_sEkoEW6DnB7HSF95eiD2Iw9mMdXTs19JzpMLmm2aO8HPkQTEgLLLFoZE2y9SEP6yl6Rqo5cr4l06gEfPRmoSYBq2RJrj2VF5v2NnlI0P8frWu7krfCyUkPxoGA5Ms9xT67LkPh9jHLVtnwFytfnyvPTnAyFXdU3wnUNqgnpdd2iv0iBqqrFOHGlJpNR5dAzZabyW9PJqnlUFiU66taljXE8SBKxJC4pbrZCyYPf5jQTfmEc6_ztTYSFtRjys6KBcGlaXk5vHkqnhL-rhbRdu1JUQZFEo1ZgqD3Cq7MIhZ8JqIoemI2ephPEdYDRu6t15wuuiYIS6CDPbuUN4tEgHrKQMDXSLhbIB_xHfKOYjTOUt8HTMKzQyK_NYNe9vMKYIOKHVlbCGm3gOdhIVlP30GDNdTZ4rKplYp9r4r6aL23g-XHsQHfv6XilbY1EmevwPizBvhkofGcfVGJux4Khvo9Kgx39um28JTygFwex2GcnsLMaoQvnZD05G15K9gaoJhFloRetjeU4kVoyO_M05h7DqKFkv2rj1YqnWqQDCty6KJtxupY9li0W5yjj5IebJY_RhGzSWUuz9APYyUsEXPDkH1x-b4T_Ap0J4pasZbqfjNS86X_fPVctJ6eHueqwAlxjt16BpwS8wyXTvc5PqtRXP71mhJja4e1sz6XCx51akvIa-ydpTeevIO6pRtBYm939i1nvW_tiQNv31gNzQACJX4C2OqgDgfNItf7Y1HWBYwBHHYnf6-tZ_XivHshqP7rBrir6d5WcW3zpnWg.1yNmEaLw5SF9gRZKBN_f_g
            - name: RUN_CONNECTOR
              value: 'false'
            - name: connector_download_repository_base_url
              value: https://signup.volumez.com/connector/
          volumeMounts:
            - name: socket-dir
              mountPath: /plugin
      volumes:
        - name: socket-dir
          emptyDir:

---               

kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: csi-nodeplugin-sioplugin
spec:
  selector:
    matchLabels:
      app: csi-nodeplugin-sioplugin
  template:
    metadata:
      labels:
        app: csi-nodeplugin-sioplugin
    spec:
      serviceAccount: csi-nodeplugin
      hostNetwork: true
      containers:
        - name: node-driver-registrar
          image: quay.io/k8scsi/csi-node-driver-registrar:v1.0.2
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "rm -rf /registration/csi-sioplugin /registration/csi-sioplugin-reg.sock"]
          args:
            - --v=5
            - --csi-address=/plugin/csi.sock
            - --kubelet-registration-path=/var/lib/kubelet/plugins/csi-sioplugin/csi.sock
          env:
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: plugin-dir
              mountPath: /plugin
            - name: registration-dir
              mountPath: /registration
        - name: vlz
          securityContext:
            privileged: true
            capabilities:
              add: ["SYS_ADMIN"]
            allowPrivilegeEscalation: true
          image: public.ecr.aws/u0q8u2v6/volumez-csi:latest
          args :
            - "--nodeid=\$(NODE_ID)"
            - "--endpoint=\$(CSI_ENDPOINT)"
            - "--volumezendpoint=\$(VOLUMEZ_ENDPOINT)"
            - "--volumezEndpointBasePath=\$(VOLUMEZ_ENDPOINT_BASE_PATH)"
            - "--volumezauthtoken=\$(VOLUMEZ_AUTH_TOKEN)"
            - "--run_connector=\$(RUN_CONNECTOR)"         
            - "--connector_download_repository_base_url=\$(connector_download_repository_base_url)"
            - "--connector_api_domain=\$(CONNECTOR_API_DOMAIN)"               
          env:
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: CSI_ENDPOINT
              value: unix://plugin/csi.sock
            - name: VOLUMEZ_ENDPOINT
              value: api.volumez.com
            - name: VOLUMEZ_ENDPOINT_BASE_PATH
              value:
            - name: VOLUMEZ_AUTH_TOKEN
              value: eyJjdHkiOiJKV1QiLCJlbmMiOiJBMjU2R0NNIiwiYWxnIjoiUlNBLU9BRVAifQ.DMI9SvdAD891pO18H_oWEahB8PKce4TREZHnV520IxL2Ub18DtspRBGMJ9Lu2Hfi1YFmKm0lmna_y8gMr_QQXrI5tK1OUr3Kwnfc1iXrGboNNo9FcdFgU2f3Pxt1o-sAykr6yiHYhBJ2lARwj1LHbNaZWXgW-8CkEwHGwz2S0NDmT1glemGCTEEQHhVRmwKlV9B4Go6BlH5qsPPSZXXfTCtLrykvlqgbi8OI-Nto6YJybcCHmbAaw7qYAekQgY53LgCOF_-Thflk_Cb5ToqeNIhis3SSJk9Cr6r2DLiaj-tHkwfz2mSFyupsQS2Vcl9x7aY5T3uxhKqdzjhctr-5CA.jvykCBRA7jRNCHey.VX8AJDQhp7xpEJ0ltuaOMRh0Y5c0yQ64I0Gc0L8xMY9AfXcDAnwc8sg1S5WMsnOMLDfZdaGLFIJ65x7E4RjxspyX4KNsWTTko8UFnTAqrkTnGOoobh2qKH3LnGzFTeZrjcFRr0HPG4P8eEwuag3rwcSNCkfLOl3PWxw912JrT9813bgrxdDcuBe2aWDJhdpBArfsM8xPQpUWs0d7hBDl2FuFSPUGq1h1Hk3oKrZoplE0SdvxG8UMcyWg7V0-0ZteJrrAuJt02GS0p960bYhBEMBoMy9ud7XOyXo3ns-GP1nF9vVASvX3Fukpm9NIVaZ1VYum8tUnvQ1QY8_jrjMwz_dY2ziKeljSKRULW_4jlSAOtETJX-CeB3KHJ5WtcBOgCorrhXFUa8sU6Uc4x7OR0b4s02BjIQzg-UYUQGbMy0iQKYOGzMoGwmsJlCwx-1iXZTrZRa5vADhPp_9L2M9yd3O1fL3cBAPdBAVbn9HnNIvcBhWidMjyzll_6Se5Kc_urAhGfR1-DDRnO_w6G2Qbwf5JXOTU2LnTov9vRYBbxuy_sEkoEW6DnB7HSF95eiD2Iw9mMdXTs19JzpMLmm2aO8HPkQTEgLLLFoZE2y9SEP6yl6Rqo5cr4l06gEfPRmoSYBq2RJrj2VF5v2NnlI0P8frWu7krfCyUkPxoGA5Ms9xT67LkPh9jHLVtnwFytfnyvPTnAyFXdU3wnUNqgnpdd2iv0iBqqrFOHGlJpNR5dAzZabyW9PJqnlUFiU66taljXE8SBKxJC4pbrZCyYPf5jQTfmEc6_ztTYSFtRjys6KBcGlaXk5vHkqnhL-rhbRdu1JUQZFEo1ZgqD3Cq7MIhZ8JqIoemI2ephPEdYDRu6t15wuuiYIS6CDPbuUN4tEgHrKQMDXSLhbIB_xHfKOYjTOUt8HTMKzQyK_NYNe9vMKYIOKHVlbCGm3gOdhIVlP30GDNdTZ4rKplYp9r4r6aL23g-XHsQHfv6XilbY1EmevwPizBvhkofGcfVGJux4Khvo9Kgx39um28JTygFwex2GcnsLMaoQvnZD05G15K9gaoJhFloRetjeU4kVoyO_M05h7DqKFkv2rj1YqnWqQDCty6KJtxupY9li0W5yjj5IebJY_RhGzSWUuz9APYyUsEXPDkH1x-b4T_Ap0J4pasZbqfjNS86X_fPVctJ6eHueqwAlxjt16BpwS8wyXTvc5PqtRXP71mhJja4e1sz6XCx51akvIa-ydpTeevIO6pRtBYm939i1nvW_tiQNv31gNzQACJX4C2OqgDgfNItf7Y1HWBYwBHHYnf6-tZ_XivHshqP7rBrir6d5WcW3zpnWg.1yNmEaLw5SF9gRZKBN_f_g
            - name: RUN_CONNECTOR
              value: 'true'
            - name: connector_download_repository_base_url
              value: https://signup.volumez.com/connector/
            - name: CONNECTOR_API_DOMAIN
              value: connector.volumez.com

          imagePullPolicy: "Always"
          volumeMounts:
            - name: plugin-dir
              mountPath: /plugin
            - name: pods-mount-dir
              mountPath: /var/lib/kubelet/pods
              mountPropagation: "Bidirectional"
            - mountPath: /lib/modules
              name: lib-modules
            - mountPath: /sys
              name: sysfs
            - mountPath: /dev
              name: dev
            - mountPath: /run/dbus
              name: systemd
      volumes:
        - name: plugin-dir
          hostPath:
            path: /var/lib/kubelet/plugins/csi-sioplugin
            type: DirectoryOrCreate
        - name: pods-mount-dir
          hostPath:
            path: /var/lib/kubelet/pods
            type: Directory
        - hostPath:
            path: /var/lib/kubelet/plugins_registry
            type: Directory
          name: registration-dir
        - name: lib-modules
          hostPath:
            path: /lib/modules
            type: Directory
        - name: sysfs
          hostPath:
            path: /sys
            type: Directory
        - name: dev
          hostPath:
            path: /dev
            type: Directory
        - name: systemd
          hostPath: 
            path: /run/dbus
            type: Directory