media_node_type = "Standard_L8as_v3"
num_of_media_node = 16
media_image_publisher="RedHat"
media_image_offer = "RHL" 
media_image_sku = "8_7"
media_image_version = "latest" 
app_node_type = "Standard_D64_v5"
num_of_app_node = 0
app_image_publisher="RedHat"
app_image_offer = "RHL" 
app_image_sku = "8_7"
app_image_version = "latest"
resource_prefix = "Volumez-easy-vm"
resource_group_location = "eastus"
zones = ["1", "2"]