resource_prefix = "netapp-vm"
resource_group_location = "eastus"
zones = ["1"]
media_node_type = "Standard_L8s_v3"
media_node_count = 3
media_image_publisher="Canonical"
media_image_offer = "0001-com-ubuntu-server-jammy" 
media_image_sku = "22_04-lts"
media_image_version = "latest" 
app_node_type = "Standard_D64_v5"
app_node_count = 0
app_image_publisher="Canonical"
app_image_offer = "0001-com-ubuntu-server-jammy" 
app_image_sku = "22_04-lts"
app_image_version = "latest"