---
kind: ConfigMap 
apiVersion: v1 
metadata:
  name: fio-job-config
data:
  fio.job: |-
    [global]
    numjobs=64
    max_latency=20s
    direct=1
    stonewall=1
    lat_percentiles=1
    filename_format=fiodata.$jobnum
    file_service_type=random
    iodepth=6
    size=15G
    group_reporting=1
    create_serialize=0
    ioengine=libaio
    sync=1
    [format]
    rw=write
    bs=128k
