---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fio
  labels:
    app: fio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fio
  template:
    metadata:
      labels:
        app: fio
    spec:
      containers:
      - name: fio
        image: joshuarobinson/fio:3.19
        command: ["sh"]
        args: ["-c", "echo ${HOSTNAME} && mkdir -p /scratch && fio /configs/fio.job --eta=never --directory=/scratch"]
        volumeMounts:
        - name: vcfg
          mountPath: /configs
        - name: vname
          mountPath: /scratch        
        imagePullPolicy: Always
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: agentpool
                operator: In
                values:
                - app
      restartPolicy: Always
      volumes:
      - name: vcfg
        configMap:
          name: fio-job-config
      - name: vname
        persistentVolumeClaim:
          claimName: vol1
